language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t lucaskc/frontend-ci-example -f Dockerfile.dev .

script:
    - docker run -e CI=true lucaskc/frontend-ci-example yarn test

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-central-1-527370786655"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
