language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t lucaskc/frontend-ci-example -f Dockerfile.dev .

script:
    - docker run -e CI=true lucaskc/frontend-ci-example yarn test
